# Generated by Django 3.1.7 on 2021-06-26 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=250)),
                ('date', models.DateField()),
                ('duration', models.IntegerField()),
                ('typeoftrip', models.CharField(choices=[('L', 'Luxury'), ('F', 'Family'), ('E', 'Expedition'), ('F', 'Frugal')], max_length=20)),
                ('travellers', models.IntegerField()),
                ('transportation', models.CharField(choices=[('C', 'Car'), ('A', 'Airplane'), ('T', 'Train'), ('B', 'Bike'), ('S', 'Ship')], default='Airplane', max_length=20)),
            ],
        ),
    ]
