# Generated by Django 3.1.7 on 2021-07-03 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacation',
            name='date',
            field=models.DateField(verbose_name='travel date'),
        ),
    ]
