# Generated by Django 3.2.4 on 2021-06-29 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210626_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Itinerary date')),
                ('activity', models.TextField(max_length=250)),
                ('vacation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.vacation')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
