# Generated by Django 3.1.7 on 2021-06-30 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20210629_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacation',
            name='typeoftrip',
        ),
        migrations.AddField(
            model_name='vacation',
            name='style',
            field=models.CharField(choices=[('L', 'Luxury'), ('F', 'Family'), ('E', 'Expedition'), ('C', 'Cheap')], default='L', max_length=10),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='transportation',
            field=models.CharField(choices=[('C', 'Car'), ('A', 'Airplane'), ('T', 'Train'), ('B', 'Bike'), ('S', 'Ship')], default='C', max_length=10),
        ),
    ]
