# Generated by Django 3.2.4 on 2021-06-30 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_packing'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacation',
            name='packing',
            field=models.ManyToManyField(to='main_app.Packing'),
        ),
    ]
