# Generated by Django 3.2.4 on 2021-06-30 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20210630_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packing',
            name='category',
            field=models.CharField(choices=[('O', 'OTHER'), ('B', 'BOTTOMS'), ('T', 'TOPS'), ('F', 'FOOTWEAR'), ('A', 'ACCESSORIES'), ('G', 'GEAR')], default='O', max_length=10),
        ),
    ]
