# Generated by Django 3.2.4 on 2021-07-01 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20210630_0141'),
        ('main_app', '0009_auto_20210629_1937'),
        ('main_app', '0010_alter_packing_category'),
    ]

    operations = [
    ]
