# Generated by Django 3.2.4 on 2021-07-01 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_merge_20210701_0112'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='packing',
            options={'ordering': ['category']},
        ),
        migrations.AddField(
            model_name='itinerary',
            name='location',
            field=models.TextField(default='banff', max_length=100),
        ),
        migrations.AlterField(
            model_name='packing',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='style',
            field=models.CharField(choices=[('L', 'Luxury'), ('F', 'Family'), ('E', 'Expedition'), ('C', 'Cheap')], default='L', max_length=1),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='transportation',
            field=models.CharField(choices=[('C', 'Car'), ('A', 'Airplane'), ('T', 'Train'), ('B', 'Bike'), ('S', 'Ship')], default='C', max_length=1),
        ),
    ]
