# Generated by Django 3.2.4 on 2021-07-01 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_auto_20210701_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerary',
            name='location',
            field=models.TextField(default='banff'),
        ),
    ]
