# Generated by Django 3.2.4 on 2021-07-01 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_alter_itinerary_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerary',
            name='location',
            field=models.CharField(default='banff', max_length=100),
        ),
    ]
