# Generated by Django 3.2.4 on 2021-07-01 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_alter_itinerary_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacation',
            name='name',
            field=models.CharField(max_length=25),
        ),
    ]
