# Generated by Django 3.2.4 on 2021-07-01 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_alter_vacation_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerary',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
