# Generated by Django 3.1.7 on 2021-07-03 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_auto_20210701_0205'),
        ('main_app', '0012_auto_20210703_0526'),
        ('main_app', '0012_auto_20210630_1925'),
    ]

    operations = [
    ]
