# Generated by Django 3.2.4 on 2021-07-03 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_merge_20210703_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerary',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='packing',
            name='category',
            field=models.CharField(choices=[('O', 'Other'), ('B', 'Bottoms'), ('T', 'Tops'), ('F', 'Footwear'), ('A', 'Accessories'), ('G', 'Gear')], default='O', max_length=10),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
