# Generated by Django 3.2.4 on 2021-07-03 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_auto_20210703_0849'),
        ('main_app', '0018_auto_20210703_0948'),
        ('main_app', '0018_auto_20210703_1547'),
    ]

    operations = [
    ]
