# Generated by Django 3.1.7 on 2021-07-03 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_auto_20210703_0849'),
        ('main_app', '0018_auto_20210703_1547'),
        ('main_app', '0018_auto_20210703_0948'),
    ]

    operations = [
    ]
