# Generated by Django 3.2.4 on 2021-07-06 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_merge_20210703_1656'),
        ('main_app', '0020_auto_20210704_0805'),
    ]

    operations = [
    ]
