# Generated by Django 3.1.7 on 2021-07-07 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210703_1509'),
        ('main_app', '0022_auto_20210706_0956'),
    ]

    operations = [
    ]
